[package]
name = "simple_setup"
version = "0.30.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
description = "Examples for the lightyearServer-client networking library for the Bevy game engine"
readme = "README.md"
repository = "https://github.com/cBournhonesque/lightyear"
keywords = ["bevy", "multiplayer", "networking", "netcode", "gamedev"]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["client", "server", "udp"]
netcode = ["lightyear/netcode"]
webtransport = ["lightyear/webtransport"]
client = ["lightyear/client", "lightyear/raw_connection"]
gui = []
server = ["lightyear/server"]
udp = ["lightyear/udp"]

[dependencies]
clap.workspace = true
lightyear = { workspace = true, features = ["replication"] }
bevy = { workspace = true, features = [
  "2d",
  "2d_bevy_render",
  "2d_api",
  "bevy_ui",
  "bevy_ui_render",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_winit",
  "bevy_window",
  "x11",
  "wayland",
] }
serde.workspace = true
async-compat.workspace = true


[lints]
workspace = true
