[package]
name = "leafwing_inputs"
version = "0.0.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
rust-version = "1.65"
publish = false

[features]
metrics = ["lightyear/metrics", "dep:metrics-exporter-prometheus"]

[dependencies]
lightyear_examples_common = { path = "../common" }
bevy_screen_diagnostics = "0.5.0"
leafwing-input-manager = "0.13"
bevy_xpbd_2d = { version = "0.4", features = ["serialize"] }
lightyear = { path = "../../lightyear", features = [
  "webtransport",
  "websocket",
  "leafwing",
  "xpbd_2d",
  "steam",
] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = { version = "1.0.75", features = [] }
tracing = "0.1"
tracing-subscriber = "0.3.17"
bevy = { version = "0.13", features = ["bevy_core_pipeline"] }
derive_more = { version = "0.99", features = ["add", "mul"] }
rand = "0.8.1"
metrics-exporter-prometheus = { version = "0.15.1", optional = true }
