[package]
name = "leafwing-inputs-3d"
version = "0.0.0"
authors = ["Nicolas Wilms <nicolas@wilms-brueggemann.de>"]
edition = "2021"
rust-version = "1.65"
publish = false

[features]
metrics = ["lightyear/metrics", "dep:metrics-exporter-prometheus"]
mock_time = ["lightyear/mock_time"]

[dependencies]
bevy_framepace = "0.14.1"
bevy-fps-counter = "0.3.0"
bevy_screen_diagnostics = "0.4.0"
leafwing-input-manager = "0.11.2"
bevy_xpbd_3d = { version = "0.3.3", features = ["serialize", "3d", "f32", "parallel"], default-features = false }
lightyear = { path = "../../lightyear", features = [
  "webtransport",
  "render",
  "leafwing",
  "xpbd_3d",
] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = { version = "1.0.75", features = [] }
tracing = "0.1"
tracing-subscriber = "0.3.17"
bevy = { version = "0.12", features = ["bevy_core_pipeline"] }
derive_more = { version = "0.99", features = ["add", "mul"] }
rand = "0.8.1"
clap = { version = "4.4", features = ["derive"] }
mock_instant = "0.3"
metrics-exporter-prometheus = { version = "0.13.0", optional = true }
bevy-inspector-egui = "0.22.1"
tokio = { version = "1.34.0", features = ["rt", "macros"] }
