FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libssl-dev ca-certificates libasound2-dev libc6
# COPY target/x86_64-unknown-linux-gnu/release/simple_box /app/examples/simple_box/simple_box
COPY examples/certificates /app/examples/certificates
COPY examples/simple_box/simple_box /app/examples/simple_box/simple_box
WORKDIR /app/examples/simple_box
RUN chmod +x simple_box
EXPOSE 4006/udp
ENTRYPOINT ["./simple_box", "server", "--port=4006", "--headless"]