//! Module to generate client inputs
//!
//! Client inputs are generated by the user and sent to the client.
//! They have to be handled separately from other messages, for several reasons:
//! - the history of inputs might need to be saved on the client to perform rollback and client-prediction
//! - we not only send the input for tick T, but we also include the inputs for the last N ticks before T. This redundancy helps ensure
//!   that the server isn't missing any client inputs even if a packet gets lost
//! - we must provide [`SystemSet`]s so that the user can order their systems before and after the input handling
//!
//! Inputs have to be defined as a single enum, which includes a variant for "no input" (for example, `None`).
//!
//! ```no_run
//! pub enum MyInput {
//!   Left,
//!   Right,
//!   Jump,
//!   None,
//! }
//! ```
//!
//! You will also need to implement a system in the [`InputSystemSet::BufferInputs`] system set to add inputs to the input buffer every tick.
//!
//! NOTE: I would advise to activate the `leafwing` feature to handle inputs via the `input_leafwing` module, instead.
//! That module is more up-to-date and has more features.
//! This module is kept for simplicity but might get removed in the future.
use crate::_reexport::ClientMarker;
use bevy::prelude::{
    not, App, Condition, EventReader, EventWriter, Events, FixedPostUpdate, FixedPreUpdate, In,
    IntoSystemConfigs, IntoSystemSetConfigs, Plugin, PostUpdate, Res, ResMut, Resource, SystemSet,
};
use tracing::{debug, error, info, trace};

use crate::channel::builder::InputChannel;
use crate::client::config::ClientConfig;
use crate::client::connection::ConnectionManager;
use crate::client::events::InputEvent;
use crate::client::metadata::GlobalMetadata;
use crate::client::prediction::plugin::is_in_rollback;
use crate::client::prediction::rollback::{Rollback, RollbackState};
use crate::client::sync::{client_is_synced, SyncSet};
use crate::inputs::native::input_buffer::InputBuffer;
use crate::inputs::native::UserAction;
use crate::prelude::{server, SharedConfig, Tick, TickManager};
use crate::protocol::Protocol;
use crate::shared::sets::InternalMainSet;
use crate::shared::tick_manager::TickEvent;

#[derive(Debug, Clone)]
pub struct InputConfig {
    /// How many consecutive packets losses do we want to handle?
    /// This is used to compute the redundancy of the input messages.
    /// For instance, a value of 3 means that each input packet will contain the inputs for all the ticks
    ///  for the 3 last packets.
    pub packet_redundancy: u16,
}

/// Resource that handles buffering and sending inputs to the server
///
/// Note: it is advised to enable the feature `leafwing` and  switch to the `LeafwingInputPlugin`,
/// which is more up-to-date and has more features.
#[derive(Debug, Resource)]
pub struct InputManager<A: UserAction> {
    pub(crate) input_buffer: InputBuffer<A>,
}

impl<A: UserAction> Default for InputManager<A> {
    fn default() -> Self {
        Self {
            input_buffer: InputBuffer::default(),
        }
    }
}

impl<A: UserAction> InputManager<A> {
    /// Get a cloned version of the input (we might not want to pop from the buffer because we want
    /// to keep it for rollback)
    pub(crate) fn get_input(&self, tick: Tick) -> Option<A> {
        self.input_buffer.get(tick).cloned()
    }

    /// Buffer a user action for the given tick
    pub fn add_input(&mut self, input: A, tick: Tick) {
        self.input_buffer.set(tick, Some(input));
    }
}

impl Default for InputConfig {
    fn default() -> Self {
        InputConfig {
            packet_redundancy: 10,
        }
    }
}

pub struct InputPlugin<P: Protocol> {
    config: InputConfig,
    _marker: std::marker::PhantomData<P>,
}

impl<P: Protocol> InputPlugin<P> {
    fn new(config: InputConfig) -> Self {
        Self {
            config,
            _marker: std::marker::PhantomData,
        }
    }
}

impl<P: Protocol> Default for InputPlugin<P> {
    fn default() -> Self {
        Self {
            config: InputConfig::default(),
            _marker: std::marker::PhantomData,
        }
    }
}

/// Input of the user for the current tick
pub struct CurrentInput<T: UserAction> {
    // TODO: should we allow a Vec of inputs? for example if a user presses multiple buttons?
    //  or would that be encoded as a combination?
    input: T,
}

impl<P: Protocol> Plugin for InputPlugin<P> {
    fn build(&self, app: &mut App) {
        // RESOURCES
        app.init_resource::<InputManager<P::Input>>();
        // EVENT
        app.add_event::<InputEvent<P::Input>>();
        // SETS
        app.configure_sets(
            FixedPreUpdate,
            (
                // no need to keep buffering inputs during rollback
                InputSystemSet::BufferInputs.run_if(not(is_in_rollback)),
                InputSystemSet::WriteInputEvent,
            )
                .chain(),
        );
        app.configure_sets(FixedPostUpdate, InputSystemSet::ClearInputEvent);
        if !app.world.resource::<ClientConfig>().is_unified() {
            app.configure_sets(
                PostUpdate,
                (
                    // handle tick events from sync before sending the message
                    InputSystemSet::ReceiveTickEvents.after(SyncSet).run_if(
                        // there are no tick events in unified mode
                        client_is_synced::<P>,
                    ),
                    // we send inputs only every send_interval
                    InputSystemSet::SendInputMessage
                        .in_set(InternalMainSet::<ClientMarker>::Send)
                        .run_if(
                            // no need to send input messages via io if we are in unified mode
                            client_is_synced::<P>,
                        ),
                    InternalMainSet::<ClientMarker>::SendPackets,
                )
                    .chain(),
            );
            app.add_systems(
                PostUpdate,
                (
                    receive_tick_events::<P::Input>.in_set(InputSystemSet::ReceiveTickEvents),
                    prepare_input_message::<P>.in_set(InputSystemSet::SendInputMessage),
                ),
            );
        }

        // SYSTEMS
        app.add_systems(
            FixedPreUpdate,
            write_input_event::<P::Input>.in_set(InputSystemSet::WriteInputEvent),
        );
        app.add_systems(
            FixedPostUpdate,
            clear_input_events::<P::Input>.in_set(InputSystemSet::ClearInputEvent),
        );

        // in case the framerate is faster than fixed-update interval, we also write/clear the events at frame limits
        // TODO: should we also write the events at PreUpdate?
        // app.add_systems(PostUpdate, clear_input_events::<P>);
    }
}

#[derive(SystemSet, Debug, Hash, PartialEq, Eq, Clone, Copy)]
pub enum InputSystemSet {
    // FIXED UPDATE
    /// System Set to write the input events to the input buffer.
    /// The User should add their system here!!
    BufferInputs,
    /// FixedUpdate system to get any inputs from the client. This should be run before the game/physics logic
    /// We access inputs via Events because of rollbacks: during rollbacks, we will re-emit past inputs as [`InputEvent`]s
    WriteInputEvent,
    /// System Set to clear the input events (otherwise bevy clears events every frame, not every tick)
    ClearInputEvent,

    // POST UPDATE
    /// In case we suddenly changed the ticks during sync, we need to update out input buffers to the new ticks
    ReceiveTickEvents,
    /// System Set to prepare the input message (in Send SystemSet)
    SendInputMessage,
}

// /// Runs at the start of every FixedUpdate schedule
// /// The USER must write this. Check what inputs were pressed and add them to the input buffer
// /// DO NOT RUN THIS DURING ROLLBACK
// fn update_input_buffer<P: Protocol>(mut client: ResMut<Client<P>>) {}
//
// // system that runs after update_input_buffer, and uses the input to update the world?
// // - NOT rollback: gets the input for the current tick from the input buffer, only runs on predicted entities.
// // - IN rollback: gets the input for the current rollback tick from the input buffer, only runs on predicted entities.
// fn apply_input() {}

/// System that clears the input events.
/// It is necessary because events are cleared every frame, but we want to clear every tick instead
fn clear_input_events<A: UserAction>(mut input_events: EventReader<InputEvent<A>>) {
    input_events.clear();
}

// Create a system that reads from the input buffer and returns the inputs of all clients for the current tick.
// The only tricky part is that events are cleared every frame, but we want to clear every tick instead
// Do it in this system because we want an input for every tick
fn write_input_event<A: UserAction>(
    tick_manager: Res<TickManager>,
    mut input_manager: ResMut<InputManager<A>>,
    mut client_input_events: EventWriter<InputEvent<A>>,
    // if we are running in unified mode, send the [`InputEvent`] directly to the server
    server_input_events: Option<ResMut<Events<server::InputEvent<A>>>>,
    metadata: Res<GlobalMetadata>,
    rollback: Option<Res<Rollback>>,
) {
    let tick = rollback.map_or(tick_manager.tick(), |rollback| match rollback.state {
        RollbackState::Default => tick_manager.tick(),
        RollbackState::ShouldRollback {
            current_tick: rollback_tick,
        } => rollback_tick,
    });
    let input = input_manager.get_input(tick);
    client_input_events.send(InputEvent::new(input_manager.get_input(tick), ()));
    if let Some(mut server_input_events) = server_input_events {
        if let Some(client_id) = metadata.client_id {
            trace!(
                "Send client input to server for local client: {}",
                client_id
            );
            server_input_events.send(server::InputEvent::new(input, client_id));
        }
        // in unified mode, there is no prediction, so we can just pop the inputs instantly
        input_manager.input_buffer.pop(tick);
    }
}

/// Receive an [`TickEvent`] signifying that the local tick has been updated,
/// and update the input buffer accordingly
fn receive_tick_events<A: UserAction>(
    mut tick_events: EventReader<TickEvent>,
    mut input_manager: ResMut<InputManager<A>>,
) {
    for tick_event in tick_events.read() {
        match tick_event {
            TickEvent::TickSnap { old_tick, new_tick } => {
                // if the tick got updated, update our inputs to match our new ticks
                if let Some(start_tick) = input_manager.input_buffer.start_tick {
                    trace!(
                        "Receive tick snap event {:?}. Updating input buffer start_tick!",
                        tick_event
                    );
                    input_manager.input_buffer.start_tick =
                        Some(start_tick + (*new_tick - *old_tick));
                };
            }
        }
    }
}

/// Take the input buffer, and prepare the input message to send to the server
fn prepare_input_message<P: Protocol>(
    connection: Option<ResMut<ConnectionManager<P>>>,
    mut input_manager: ResMut<InputManager<P::Input>>,
    config: Res<ClientConfig>,
    tick_manager: Res<TickManager>,
) {
    let Some(mut connection) = connection else {
        return;
    };

    let current_tick = tick_manager.tick();
    // TODO: the number of messages should be in SharedConfig
    trace!(tick = ?current_tick, "prepare_input_message");
    // TODO: instead of 15, send ticks up to the latest yet ACK-ed input tick
    //  this means we would also want to track packet->message acks for unreliable channels as well, so we can notify
    //  this system what the latest acked input tick is?

    // we send redundant inputs, so that if a packet is lost, we can still recover
    let num_tick: u16 = ((config.shared.client_send_interval.as_nanos()
        / config.shared.tick.tick_duration.as_nanos())
        + 1)
    .try_into()
    .unwrap();
    let redundancy = config.input.packet_redundancy;
    // let redundancy = 3;
    let message_len = redundancy * num_tick;
    // TODO: we can either:
    //  - buffer an input message at every tick, and not require that much redundancy
    //  - buffer an input every frame; and require some redundancy (number of tick per frame)
    //  - or buffer an input only when we are sending, and require more redundancy
    // let message_len = 20 as u16;
    let message = input_manager
        .input_buffer
        .create_message(tick_manager.tick(), message_len);
    // all inputs are absent
    if !message.is_empty() {
        // TODO: should we provide variants of each user-facing function, so that it pushes the error
        //  to the ConnectionEvents?
        trace!(
            ?current_tick,
            "sending input message: {:?}",
            message.end_tick
        );
        connection
            .send_message::<InputChannel, _>(message)
            .unwrap_or_else(|err| {
                error!("Error while sending input message: {:?}", err);
            })
    }
    // NOTE: actually we keep the input values! because they might be needed when we rollback for client prediction
    // TODO: figure out when we can delete old inputs. Basically when the oldest prediction group tick has passed?
    //  maybe at interpolation_tick(), since it's before any latest server update we receive?

    // delete old input values
    let interpolation_tick = connection.sync_manager.interpolation_tick(&tick_manager);
    input_manager.input_buffer.pop(interpolation_tick);
    // .pop(current_tick - (message_len + 1));
}
