[package]
name = "deterministic_replication"
version = "0.0.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition.workspace = true
publish = false

[features]
default = ["client", "gui", "server", "netcode", "udp"]
client = ["lightyear_examples_common/client"]
gui = ["lightyear_examples_common/gui"]
server = ["lightyear_examples_common/server"]
netcode = ["lightyear_examples_common/netcode"]
udp = ["lightyear_examples_common/udp"]

[dependencies]
lightyear = { workspace = true, features = [
  "interpolation",
  "prediction",
  "replication",
  "leafwing",
] }
lightyear_avian2d.workspace = true
#lightyear_avian2d = { workspace = true, features = ["2d"]}
lightyear_examples_common.workspace = true
lightyear_frame_interpolation.workspace = true
leafwing-input-manager.workspace = true
avian2d = { workspace = true, features = [
  "2d",
  "f32",
  "parry-f32",
  "parallel",
  "serialize",
  "enhanced-determinism",
] }

serde.workspace = true
bevy.workspace = true

[package.metadata.bevy_cli.web]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
default-features = false
features = ["client", "netcode"]

[lints]
workspace = true
