name: Deploy book

on:
  pull_request:
    paths:
      - "book/**"
      - ".github/workflows/website.yaml"
  push:
    paths:
      - "book/**"
      - ".github/workflows/website.yaml"

concurrency:
  group: pages-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdbook-mermaid
        run: CARGO_BUILD_JOBS=4 cargo install mdbook-mermaid --locked

      - name: Build Book
        run: |
          cd book
          mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: book/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
